In [25]:
import pandas as pd
from  sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [26]:
df=pd.read_csv('Housing (1).csv')

In [27]:
x=df.drop('price',axis=1)
y=df['price']

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
num_cal=x.select_dtypes(exclude='object').columns
cat_cal=x.select_dtypes(include='object').columns

C:\Users\DELL\AppData\Local\Temp\ipykernel_12496\2240456210.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cal=x.select_dtypes(include='object').columns

In [30]:
scalar=StandardScaler()
lable=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

In [31]:
x_train_num=scalar.fit_transform(x_train[num_cal])
x_test_num=scalar.transform(x_test[num_cal])

In [32]:
x_train_cat=lable.fit_transform(x_train[cat_cal])
x_test_cat=lable.transform(x_test[cat_cal])
x_train_cat

array([[0., 1., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       ...,
       [0., 1., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(436, 15))

In [33]:
x_train_cat=pd.DataFrame(
    x_train_cat,
    columns=lable.get_feature_names_out(cat_cal),
    index=x_train.index
)
x_train_cat

,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
46,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
93,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
335,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
412,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
471,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
106,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
270,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
435,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
102,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0

In [34]:
x_test_cat=pd.DataFrame(
    x_test_cat,
    columns=lable.get_feature_names_out(cat_cal),
    index=x_test.index
)

In [35]:
x_train_num=pd.DataFrame(x_train_num,columns=num_cal,index=x_train.index)
x_train_num

         area  bedrooms  bathrooms   stories   parking
46   0.384168  0.055271   1.539173  2.587644  0.367957
93   0.929181  0.055271   1.539173 -0.912499  2.709987
335 -0.607755 -1.283514  -0.557950 -0.912499  1.538972
412 -1.155492  0.055271  -0.557950  0.254215 -0.803059
471 -0.637730  0.055271  -0.557950  0.254215 -0.803059
..        ...       ...        ...       ...       ...
71   0.384168  1.394055   1.539173  2.587644 -0.803059
106  0.134371  1.394055   1.539173 -0.912499 -0.803059
270 -0.297097  0.055271   1.539173  1.420929  0.367957
435 -0.506019 -1.283514  -0.557950 -0.912499 -0.803059
102  0.157080  0.055271   1.539173  2.587644  0.367957

[436 rows x 5 columns]

In [36]:
x_test_num=pd.DataFrame(
    x_test_num,
    columns=num_cal,
    index=x_test.index
)

In [37]:
x_train_final=pd.concat([x_train_num,x_train_cat],axis=1)
x_test_final=pd.concat([x_test_num,x_test_cat],axis=1)

In [38]:
model=LinearRegression()
model.fit(x_train_final,y_train)

LinearRegression()

In [39]:
y_pred=model.predict(x_test_final)

In [40]:
r2_score(y_test,y_pred)

0.6529242642153172

In [41]:
mean_absolute_error(y_test,y_pred)

970043.4039201644

In [42]:
mean_squared_error(y_test,y_pred)

1754318687330.6694