In [69]:
import pandas  as  pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.linear_model import  LogisticRegression
from sklearn.metrics import  accuracy_score

In [70]:
df=pd.read_csv('loan_data.csv')

In [71]:
x=df.drop('loan_status',axis=1)
y=df['loan_status']

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [73]:
num_cal=x.select_dtypes(exclude='object').columns
cat_cal=x.select_dtypes(include='object').columns

C:\Users\DELL\AppData\Local\Temp\ipykernel_16488\2240456210.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cal=x.select_dtypes(include='object').columns

In [74]:
scaler=StandardScaler()
lable=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

In [75]:
x_train_num=scaler.fit_transform(x_train[num_cal])
x_test_num=scaler.transform(x_test[num_cal])

In [76]:
x_train_cat=lable.fit_transform(x_train[cat_cal])
x_test_cat=lable.transform(x_test[cat_cal])
x_train_cat

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 1., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(36000, 19))

In [77]:
x_train_cat=pd.DataFrame(
    x_train_cat,
    columns=lable.get_feature_names_out(cat_cal),
    index=x_train.index
)
x_train_cat

,person_gender_female,person_gender_male,person_education_Associate,person_education_Bachelor,person_education_Doctorate,person_education_High School,person_education_Master,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_No,previous_loan_defaults_on_file_Yes
25180,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
12555,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29153,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
23838,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
35686,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
44732,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
38158,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
860,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15795,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [78]:
x_test_cat=pd.DataFrame(
    x_test_cat,
    columns=lable.get_feature_names_out(cat_cal),
    index=x_test.index
)

In [79]:
x_train_num=pd.DataFrame(x_train_num,columns=num_cal,index=x_train.index)
x_train_num

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score
25180,1.039475,0.194225,0.931186,0.859025,0.577910,0.119054,0.816732,-0.032444
12555,-0.456186,-0.089962,-0.395014,0.383393,0.286925,0.233921,-0.478914,0.524687
29153,2.202767,2.828167,2.091610,2.285919,-0.211430,-0.799885,1.334990,1.002227
23838,-0.123817,0.158772,-0.229239,0.002888,2.052907,-0.455283,0.298474,0.166531
35686,-0.123817,0.049373,0.268086,-0.399971,0.658182,-0.685018,-0.738043,1.459871
...,...,...,...,...,...,...,...,...
11284,-0.290001,0.091197,0.102311,0.165396,-1.663014,-0.225548,-0.478914,-1.465066
44732,-0.456186,-0.536266,-0.395014,-0.587529,0.230066,0.348788,-0.478914,0.285916
38158,0.873291,-0.261045,0.599636,0.178396,-0.087677,0.463655,0.816732,0.385404
860,-0.290001,1.144986,0.102311,1.651744,2.337203,-0.340416,-0.738043,-0.569677
15795,-0.290001,1.522453,-0.229239,0.859025,0.002628,-0.799885,-0.738043,0.624174

In [80]:
x_test_num=pd.DataFrame(
    x_test_num,
    columns=num_cal,
    index=x_test.index
)

In [81]:
x_train_final=pd.concat([x_train_num,x_train_cat],axis=1)
x_test_final=pd.concat([x_test_num,x_test_cat],axis=1)

In [82]:
model=LogisticRegression()
model.fit(x_train_final,y_train)

LogisticRegression()

In [83]:
y_pred=model.predict(x_test_final)

In [84]:
accuracy_score(y_test,y_pred)

0.8945555555555555